main: mup.nolan.mupplugin.MupPlugin
name: MupPlugin
author: nołanmup
description: szypkiplugin2011
version: 0.2

api-version: 1.18
softdepend: [PlaceholderAPI, Vault]

commands:
  mupplugin:
    aliases: mup
#  list:
#    aliases: [ls, who]
  sortowanie:
    aliases: sort
  butelka:
    description: dajexp
#  feed:
#    description: amciu
#  heal:
#    description: zycko
  galeria:
    description: poka ity
  check:
    description: co my tu mamy
  discord:
    description: dicord wiadomosci jakies

permissions:
  mup.cmd.mupplugin:
    default: op
  mup.cmd.sortowanie:
    default: op
  mup.cmd.bottlexp:
    default: op
  mup.cmd.feed:
    default: op
  mup.cmd.feed.others:
    default: op
  mup.cmd.feed.level:
    default: op
  mup.cmd.heal:
    default: op
  mup.cmd.heal.others:
    default: op
  mup.cmd.heal.level:
    default: op
  mup.cmd.gallery:
    default: op
  mup.cmd.gallery.edit-others:
    default: op
  mup.antiafk.exempt:
    default: op
  mup.cmd.check:
    default: op
  mup.chatpatrol.exempt.punish:
    default: op
  mup.chatpatrol.exempt.replace:
    description: omija cenzurowanie
  mup.chatpatrol.exempt.caps:
    default: op
  mup.chatpatrol.exempt.cooldown:
    default: op
  mup.chatpatrol.exempt.flood:
    default: op
  mup.chatpatrol.exempt.spam:
    default: op
  mup.chatpatrol.notify:
    default: op
  mup.cmd.discord:
    default: op
  mup.cmd.discord.link:
    default: op
  mup.cmd.discord.unlink:
    default: op
